const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

// Configure directories
const INPUT_DIR = path.join(__dirname, 'raw-images');
const OUTPUT_DIR = path.join(__dirname, 'assets/images');
const HTML_OUTPUT_FILE = path.join(__dirname, 'gallery-fragment.html');

// --- GALLERY EXCLUSION CONFIGURATION ---
// These files will still be converted to WebP, but they won't appear on the HTML page
const EXCLUDED_FROM_GALLERY = [
  'draft-image.jpg',
  'private-photo.png'
];

// Any source file starting with this prefix is kept out of the HTML page
const EXCLUDE_PREFIX = '_';
// ---------------------------------------

// Ensure directories exist
if (!fs.existsSync(OUTPUT_DIR)){
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

// Read the raw images folder
fs.readdir(INPUT_DIR, async (err, files) => {
  if (err) {
    console.error("Could not read directory.", err);
    process.exit(1);
  }

  // Filter out non-image files (all of these will be processed/converted)
  const imageFiles = files.filter(file => 
    ['.jpg', '.jpeg', '.png'].includes(path.extname(file).toLowerCase())
  );

  let htmlCards = '';

  // Process images sequentially using an async loop
  for (const file of imageFiles) {
    const fileExtension = path.extname(file);
    const fileNameWithoutExt = path.basename(file, fileExtension);
    const outputFileName = `${fileNameWithoutExt}.webp`;
    const outputFilePath = path.join(OUTPUT_DIR, outputFileName);
    const inputFilePath = path.join(INPUT_DIR, file);

    try {
      // Check if the output webp image already exists
      const fileAlreadyProcessed = fs.existsSync(outputFilePath);

      if (!fileAlreadyProcessed) {
        // 1. Convert and compress image via Sharp only if it doesn't exist
        await sharp(inputFilePath)
          .webp({ quality: 80 })
          .toFile(outputFilePath);
        
        console.log(`✓ Processed: ${file} → ${outputFileName}`);
      } else {
        // Log skip behavior to keep console clean
        console.log(`• Skipped (Already Converted): ${outputFileName}`);
      }

      // 2. Determine if this file should be excluded from the HTML gallery markup
      const isExcluded = EXCLUDED_FROM_GALLERY.includes(file) || file.startsWith(EXCLUDE_PREFIX);

      if (!isExcluded) {
        const altText = fileNameWithoutExt.replace(/[-_]/g, ' ');

        htmlCards += `
    <!-- Gallery Card: ${outputFileName} -->
    <div class="w-[calc(50%-8px)] md:w-[calc(25%-12px)] flex-shrink-0 snap-start aspect-square bg-brand-light border border-brand-border overflow-hidden relative group cursor-pointer">
      <img 
        src="assets/images/${outputFileName}" 
        alt="${altText}" 
        class="w-full h-full object-cover grayscale contrast-125 group-hover:scale-105 group-hover:grayscale-0 transition-all duration-500"
        loading="lazy"
      />
      <div class="absolute inset-0 bg-brand-black/40 group-hover:opacity-0 transition-opacity"></div>
    </div>`;
      } else {
        console.log(`- Excluded from HTML gallery: ${file}`);
      }

    } catch (error) {
      console.error(` ✕ Error processing ${file}:`, error);
    }
  }

  // 3. Assemble the full horizontal-snap outer container layout
  const fullHtmlComponent = `<!-- AUTOMATICALLY GENERATED BY NODE SCRIPT - DO NOT EDIT MANUALLY -->
<div class="relative group/gallery">
  <h3 class="font-display text-lg font-bold tracking-wider uppercase mb-6 flex items-center gap-2 text-brand-accent">
    <i data-lucide="aperture" class="w-5 h-5"></i> FIELD PHOTOS
  </h3>
  
  <div class="relative w-full overflow-visible">
    
    <!-- Left Scroll Button -->
    <button id="gallery-left" 
            class="absolute -left-4 top-1/2 -translate-y-1/2 bg-brand-black/80 hover:bg-brand-border text-stone-100 border border-brand-border p-2.5 rounded-full transition-all duration-200 backdrop-blur-sm z-10 opacity-0 group-hover/gallery:opacity-100 disabled:opacity-0 disabled:pointer-events-none shadow-xl focus:outline-none" 
            disabled 
            title="Scroll Left">
      <i data-lucide="chevron-left" class="w-5 h-5"></i>
    </button>

    <!-- Horizontal Scrollable Container -->
    <div id="photo-scroll-container" 
         class="flex gap-4 overflow-x-auto scroll-smooth snap-x snap-mandatory [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none] w-full py-1">
      ${htmlCards.trim()}
    </div>

    <!-- Right Scroll Button -->
    <button id="gallery-right" 
            class="absolute -right-4 top-1/2 -translate-y-1/2 bg-brand-black/80 hover:bg-brand-border text-stone-100 border border-brand-border p-2.5 rounded-full transition-all duration-200 backdrop-blur-sm z-10 opacity-0 group-hover/gallery:opacity-100 disabled:opacity-0 disabled:pointer-events-none shadow-xl focus:outline-none" 
            title="Scroll Right">
      <i data-lucide="chevron-right" class="w-5 h-5"></i>
    </button>

  </div>
</div>
`;

  // 4. Write the HTML fragment to disk
  fs.writeFileSync(HTML_OUTPUT_FILE, fullHtmlComponent, 'utf8');
  console.log(`\n🎉 Success! Horizontal Scroll Gallery HTML written to: ${HTML_OUTPUT_FILE}`);
});